// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama.GenderTest;

import java.util.List;
import java.util.Random;
import org.motechproject.tama.Gender;
import org.springframework.stereotype.Component;

privileged aspect GenderDataOnDemand_Roo_DataOnDemand {
    
    declare @type: GenderDataOnDemand: @Component;
    
    private Random GenderDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Gender> GenderDataOnDemand.data;
    
    public Gender GenderDataOnDemand.getNewTransientGender(int index) {
        org.motechproject.tama.Gender obj = new org.motechproject.tama.Gender();
        setType(obj, index);
        return obj;
    }
    
    public void GenderDataOnDemand.setType(Gender obj, int index) {
        java.lang.String type = "type_" + index;
        obj.setType(type);
    }
    
    public Gender GenderDataOnDemand.getSpecificGender(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Gender obj = data.get(index);
        return Gender.findGender(obj.getId());
    }
    
    public Gender GenderDataOnDemand.getRandomGender() {
        init();
        Gender obj = data.get(rnd.nextInt(data.size()));
        return Gender.findGender(obj.getId());
    }
    
    public boolean GenderDataOnDemand.modifyGender(Gender obj) {
        return false;
    }
    
    public void GenderDataOnDemand.init() {
        data = org.motechproject.tama.Gender.findGenderEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Gender' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.motechproject.tama.Gender>();
        for (int i = 0; i < 10; i++) {
            org.motechproject.tama.Gender obj = getNewTransientGender(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
