package org.motechproject.tama.ivr.domain;

public enum CallState {
    STARTED, AUTHENTICATED, ALL_TREES_COMPLETED, SYMPTOM_REPORTING, SYMPTOM_REPORTING_TREE, OUTBOX, HEALTH_TIPS, END_OF_FLOW, PUSH_MESSAGES_COMPLETE;
}
