// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama;

import java.lang.String;

privileged aspect Initials_Roo_JavaBean {
    
    public String Initials.getType() {
        return this.type;
    }
    
    public void Initials.setType(String type) {
        this.type = type;
    }
    
}
