// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama;

import java.lang.String;

privileged aspect Title_Roo_ToString {
    
    public String Title.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Type: ").append(getType());
        return sb.toString();
    }
    
}
