// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama;

import java.util.List;
import java.util.Random;
import org.motechproject.tama.Initials;
import org.springframework.stereotype.Component;

privileged aspect InitialsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: InitialsDataOnDemand: @Component;
    
    private Random InitialsDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Initials> InitialsDataOnDemand.data;
    
    public Initials InitialsDataOnDemand.getNewTransientInitials(int index) {
        org.motechproject.tama.Initials obj = new org.motechproject.tama.Initials();
        setType(obj, index);
        return obj;
    }
    
    public void InitialsDataOnDemand.setType(Initials obj, int index) {
        java.lang.String type = "type_" + index;
        obj.setType(type);
    }
    
    public Initials InitialsDataOnDemand.getSpecificInitials(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Initials obj = data.get(index);
        return Initials.findInitials(obj.getId());
    }
    
    public Initials InitialsDataOnDemand.getRandomInitials() {
        init();
        Initials obj = data.get(rnd.nextInt(data.size()));
        return Initials.findInitials(obj.getId());
    }
    
    public boolean InitialsDataOnDemand.modifyInitials(Initials obj) {
        return false;
    }
    
    public void InitialsDataOnDemand.init() {
        data = org.motechproject.tama.Initials.findInitialsEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Initials' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.motechproject.tama.Initials>();
        for (int i = 0; i < 10; i++) {
            org.motechproject.tama.Initials obj = getNewTransientInitials(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
