dialect "mvel"
import org.motechproject.tama.domain.PatientMedicalConditions;

global java.util.List tree;

rule "Regimen1"
    when
        PatientMedicalConditions(regimenName == "Regimen I");
    then
end

rule "N1" extends "Regimen1"
    when
        $n1 : PatientMedicalConditions(age > 50);
    then
end

rule "N2" extends "Regimen1"
    when
        not(PatientMedicalConditions(age > 50)) && PatientMedicalConditions(cd4Count <= 50);
    then
end

rule "N3" extends "N1"
    when
        PatientMedicalConditions(cd4Count <= 50);
    then
end

rule "Tree_Regimen1_1" extends "N2"
    when
    then
        tree.add("Regimen1_1");
end

rule "Tree_Regimen1_2" extends "Regimen1"
    when
        not(PatientMedicalConditions(cd4Count <= 50))
    then
        tree.add("Regimen1_2");
end

rule "Tree_Regimen1_3" extends "N3"
    when
    then
        tree.add("Regimen1_3");
end

rule "Tree_Regimen1_4" extends "N1"
    when
        not(PatientMedicalConditions(cd4Count <= 50))
    then
        tree.add("Regimen1_4");
end