// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama.integration.domain.patient;

import org.motechproject.tama.unit.domain.patient.PatientTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PatientIntegrationTest_Roo_Configurable {
    
    declare @type: PatientTest: @Configurable;
    
}
