// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama.integration.domain.patient;

import org.motechproject.tama.domain.Doctor;
import org.motechproject.tama.domain.Gender;
import org.motechproject.tama.domain.Patient;
import org.motechproject.tama.integration.domain.doctor.DoctorDataOnDemand;
import org.motechproject.tama.integration.domain.gender.GenderDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Random;

privileged aspect PatientDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PatientDataOnDemand: @Component;
    
    private Random PatientDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Patient> PatientDataOnDemand.data;
    
    @Autowired
    private GenderDataOnDemand PatientDataOnDemand.genderDataOnDemand;
    
    @Autowired
    private DoctorDataOnDemand PatientDataOnDemand.doctorDataOnDemand;
    
    public Patient PatientDataOnDemand.getNewTransientPatient(int index) {
        Patient obj = new Patient();
        setPatientId(obj, index);
        setMobilePhoneNumber(obj, index);
        setDateOfBirth(obj, index);
        setTravelTimeToClinicInDays(obj, index);
        setTravelTimeToClinicInHours(obj, index);
        setTravelTimeToClinicInMinutes(obj, index);
        setGender(obj, index);
        setPrincipalDoctor(obj, index);
        return obj;
    }
    
    public void PatientDataOnDemand.setPatientId(Patient obj, int index) {
        java.lang.String patientId = "patientId_" + index;
        obj.setPatientId(patientId);
    }
    
    public void PatientDataOnDemand.setMobilePhoneNumber(Patient obj, int index) {
        java.lang.String mobilePhoneNumber = "mobilePhoneNumber_" + index;
        obj.setMobilePhoneNumber(mobilePhoneNumber);
    }
    
    public void PatientDataOnDemand.setDateOfBirth(Patient obj, int index) {
        java.util.Date dateOfBirth = new java.util.Date(new java.util.Date().getTime() - 10000000L);
        obj.setDateOfBirth(dateOfBirth);
    }
    
    public void PatientDataOnDemand.setTravelTimeToClinicInDays(Patient obj, int index) {
        int travelTimeToClinicInDays = index;
        obj.setTravelTimeToClinicInDays(travelTimeToClinicInDays);
    }
    
    public void PatientDataOnDemand.setTravelTimeToClinicInHours(Patient obj, int index) {
        int travelTimeToClinicInHours = index;
        obj.setTravelTimeToClinicInHours(travelTimeToClinicInHours);
    }
    
    public void PatientDataOnDemand.setTravelTimeToClinicInMinutes(Patient obj, int index) {
        int travelTimeToClinicInMinutes = index;
        obj.setTravelTimeToClinicInMinutes(travelTimeToClinicInMinutes);
    }
    
    public void PatientDataOnDemand.setGender(Patient obj, int index) {
        Gender gender = genderDataOnDemand.getRandomGender();
        obj.setGender(gender);
    }
    
    public void PatientDataOnDemand.setPrincipalDoctor(Patient obj, int index) {
        Doctor principalDoctor = doctorDataOnDemand.getRandomDoctor();
        obj.setPrincipalDoctor(principalDoctor);
    }
    
    public Patient PatientDataOnDemand.getSpecificPatient(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Patient obj = data.get(index);
        return Patient.findPatient(obj.getId());
    }
    
    public Patient PatientDataOnDemand.getRandomPatient() {
        init();
        Patient obj = data.get(rnd.nextInt(data.size()));
        return Patient.findPatient(obj.getId());
    }
    
    public boolean PatientDataOnDemand.modifyPatient(Patient obj) {
        return false;
    }
    
    public void PatientDataOnDemand.init() {
        data = Patient.findPatientEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Patient' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<Patient>();
        for (int i = 0; i < 10; i++) {
            Patient obj = getNewTransientPatient(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
