// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama.domain;

import java.util.List;

privileged aspect Drug_Roo_Entity {
    
	declare parents : Drug extends CouchDocument;
    
    public void Drug.persist() {
    }
    
    public void Drug.remove() {
    }
    
    public void Drug.flush() {
    }
    
    public void Drug.clear() {
    }
    
    public Drug Drug.merge() {
		return null;
    }
    
    public static long Drug.countDrugs() {
		return 0;
    }
    
    public static List<Drug> Drug.findAllDrugs() {
		return null;
    }
    
    public static Drug Drug.findDrug(Long id) {
		return null;
    }
    
    public static List<Drug> Drug.findDrugEntries(int firstResult, int maxResults) {
		return null;
    }
    
}
