// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama.domain;


privileged aspect DrugDosage_Roo_Entity {
    
    declare parents : DrugDosage extends BaseEntity;
}
