// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama.domain;

import java.util.Set;

privileged aspect Drug_Roo_JavaBean {
    
    public String Drug.getName() {
        return this.name;
    }
    
    public void Drug.setName(String name) {
        this.name = name;
    }
    
    public Set<Brand> Drug.getBrands() {
        return this.brands;
    }
    
    public void Drug.setBrands(Set<Brand> brands) {
        this.brands = brands;
    }
    
}
