// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama.domain;

import java.util.List;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.motechproject.tama.repository.Drugs;
import org.springframework.beans.factory.annotation.Autowired;

privileged aspect Drug_Roo_Entity {
    
	declare parents : Drug extends CouchDocument;

	@Autowired
	transient Drugs Drug.drugs; 
    
    public void Drug.persist() {
    	this.drugs.add(this);
    }
    
    public void Drug.remove() {
    }
    
    public void Drug.flush() {
    }
    
    public void Drug.clear() {
    }
    
    public Drug Drug.merge() {
		return null;
    }
    
    public static long Drug.countDrugs() {
		return drugs().count();
    }
    
    public static List<Drug> Drug.findAllDrugs() {
		return null;
    }
    
    public static Drugs drugs(){
    	return new Drug().drugs;
    }
    
    public static Drug Drug.findDrug(String id) {
		return drugs().get(id);
    }
    
    public static List<Drug> Drug.findDrugEntries(int firstResult, int maxResults) {
		return null;
    }

    @JsonIgnore
	public Drugs Drug.getDrugs() {
		return drugs;
	}

	public void Drug.setDrugs(Drugs drugs) {
		this.drugs = drugs;
	}
}
