// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama.domain;

import java.util.Date;

privileged aspect DrugDosage_Roo_JavaBean {
    
    public String DrugDosage.getDrugId() {
        return this.drugId;
    }
    
    public void DrugDosage.setDrugId(String drugId) {
        this.drugId = drugId;
    }
    
    public String DrugDosage.getBrandId() {
        return this.brandId;
    }
    
    public void DrugDosage.setBrandId(String brandId) {
        this.brandId = brandId;
    }
    
    public Dosage DrugDosage.getDosage() {
        return this.dosage;
    }
    
    public void DrugDosage.setDosage(Dosage dosage) {
        this.dosage = dosage;
    }
    
    public Date DrugDosage.getStartDate() {
        return this.startDate;
    }
    
    public void DrugDosage.setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    
    public Date DrugDosage.getEndDate() {
        return this.endDate;
    }
    
    public void DrugDosage.setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    
    public String DrugDosage.getAdvice() {
        return this.advice;
    }
    
    public void DrugDosage.setAdvice(String advice) {
        this.advice = advice;
    }
    
    public String DrugDosage.getMealAdviceId() {
        return this.mealAdviceId;
    }
    
    public void DrugDosage.setMealAdviceId(String mealAdviceId) {
        this.mealAdviceId = mealAdviceId;
    }
    
}
