// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama.domain;


privileged aspect Gender_Roo_JavaBean {
    
    public String Gender.getType() {
        return this.type;
    }
    
    public void Gender.setType(String type) {
        this.type = type;
    }
    
}
