// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama.domain;

import java.lang.String;

privileged aspect IVRLanguage_Roo_JavaBean {
    
    public String IVRLanguage.getName() {
        return this.name;
    }
    
    public void IVRLanguage.setName(String name) {
        this.name = name;
    }
    
}
