// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama.domain;

import java.lang.String;

privileged aspect MealAdviceType_Roo_JavaBean {
    
    public String MealAdviceType.getType() {
        return this.type;
    }
    
    public void MealAdviceType.setType(String type) {
        this.type = type;
    }
    
}
