// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama.domain;

import java.lang.String;

privileged aspect Phone_Roo_JavaBean {
    
    public String Phone.getPhonNnumber() {
        return this.phonNnumber;
    }
    
    public void Phone.setPhonNnumber(String phonNnumber) {
        this.phonNnumber = phonNnumber;
    }
    
}
