import org.motechproject.tamahealthtip.domain.HealthTipParams;
import java.util.Arrays;
import java.util.List;

global java.util.Map healthTips;

rule "Less than 1 month into ART"
    when
        HealthTipParams(numberOfMonthsSinceTreatmentStarted < 1)
    then
        for (String file : Arrays.asList("HT001a", "HT002a", "HT003a", "HT004a", "HT005a","HT011a", "HT012a", "HT013a", "HT017a", "HT018a")) {
            healthTips.put(file, "2");
        }

        for (String file : Arrays.asList("HT033a", "HT034a", "HT035a", "HT036a", "HT037a", "HT038a", "HT039a", "HT040a")) {
            healthTips.put(file, "3");
        }
end

rule "Less than 1 month into ART and patient on daily pill reminder"
    when
        HealthTipParams(numberOfMonthsSinceTreatmentStarted < 1)
        HealthTipParams(patientOnDailyPillReminder == "true")
    then
        for (String file : Arrays.asList("HT014a", "HT019a", "HT021a")) {
            healthTips.put(file, "2");
        }
end

rule "Less than 1 month into ART and patient not on daily pill reminder"
    when
        HealthTipParams(numberOfMonthsSinceTreatmentStarted < 1)
        HealthTipParams(patientOnDailyPillReminder == "false")
    then
        for (String file : Arrays.asList("HT015a", "HT020a", "HT022a")) {
            healthTips.put(file, "2");
        }
end

rule "Dosage Missed Last Week"
    when
        HealthTipParams(dosageMissedLastWeek == "true")
    then
        for (String file : Arrays.asList("HT004a", "HT002a", "HT011a", "HT012a")) {
            healthTips.put(file, "1");
        }
end

rule "Dosage Missed Last Week and user on daily reminder"
    when
        HealthTipParams(dosageMissedLastWeek == "true")
        HealthTipParams(patientOnDailyPillReminder == "true")
    then
        for (String file : Arrays.asList("HT021a", "HT014a")) {
            healthTips.put(file, "1");
        }
end

rule "Dosage Missed Last Week and user on four day recall"
    when
        HealthTipParams(dosageMissedLastWeek == "true")
        HealthTipParams(patientOnDailyPillReminder == "false")
    then
        for (String file : Arrays.asList("HT022a", "HT015a")) {
            healthTips.put(file, "1");
        }
end