// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.motechproject.tama.integration.domain.ivrlanguage;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.motechproject.tama.domain.IVRLanguage;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect IVRLanguageIntegrationTest_Roo_IntegrationTest {
    
    declare @type: IVRLanguageIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: IVRLanguageIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    @Autowired
    private IVRLanguageDataOnDemand IVRLanguageIntegrationTest.dod;
    
    @Test
    public void IVRLanguageIntegrationTest.testCountIVRLanguages() {
        org.junit.Assert.assertNotNull("Data on demand for 'IVRLanguage' failed to initialize correctly", dod.getRandomIVRLanguage());
        long count = IVRLanguage.countIVRLanguages();
        org.junit.Assert.assertTrue("Counter for 'IVRLanguage' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void IVRLanguageIntegrationTest.testFindIVRLanguage() {
        IVRLanguage obj = dod.getRandomIVRLanguage();
        org.junit.Assert.assertNotNull("Data on demand for 'IVRLanguage' failed to initialize correctly", obj);
        String id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'IVRLanguage' failed to provide an identifier", id);
        obj = IVRLanguage.findIVRLanguage(id);
        org.junit.Assert.assertNotNull("Find method for 'IVRLanguage' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'IVRLanguage' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void IVRLanguageIntegrationTest.testFindAllIVRLanguages() {
        org.junit.Assert.assertNotNull("Data on demand for 'IVRLanguage' failed to initialize correctly", dod.getRandomIVRLanguage());
        long count = IVRLanguage.countIVRLanguages();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'IVRLanguage', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<IVRLanguage> result = IVRLanguage.findAllIVRLanguages();
        org.junit.Assert.assertNotNull("Find all method for 'IVRLanguage' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'IVRLanguage' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void IVRLanguageIntegrationTest.testFindIVRLanguageEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'IVRLanguage' failed to initialize correctly", dod.getRandomIVRLanguage());
        long count = IVRLanguage.countIVRLanguages();
        if (count > 20) count = 20;
        java.util.List<IVRLanguage> result = IVRLanguage.findIVRLanguageEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'IVRLanguage' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'IVRLanguage' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void IVRLanguageIntegrationTest.testFlush() {
        IVRLanguage obj = dod.getRandomIVRLanguage();
        org.junit.Assert.assertNotNull("Data on demand for 'IVRLanguage' failed to initialize correctly", obj);
        String id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'IVRLanguage' failed to provide an identifier", id);
        obj = IVRLanguage.findIVRLanguage(id);
        org.junit.Assert.assertNotNull("Find method for 'IVRLanguage' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyIVRLanguage(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'IVRLanguage' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IVRLanguageIntegrationTest.testMerge() {
        IVRLanguage obj = dod.getRandomIVRLanguage();
        org.junit.Assert.assertNotNull("Data on demand for 'IVRLanguage' failed to initialize correctly", obj);
        String id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'IVRLanguage' failed to provide an identifier", id);
        obj = IVRLanguage.findIVRLanguage(id);
        boolean modified =  dod.modifyIVRLanguage(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        IVRLanguage merged = (IVRLanguage) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'IVRLanguage' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void IVRLanguageIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'IVRLanguage' failed to initialize correctly", dod.getRandomIVRLanguage());
        IVRLanguage obj = dod.getNewTransientIVRLanguage(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'IVRLanguage' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'IVRLanguage' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'IVRLanguage' identifier to no longer be null", obj.getId());
    }
    
    @Test(expected = org.ektorp.DocumentNotFoundException.class)
    public void IVRLanguageIntegrationTest.testRemove() {
        IVRLanguage obj = dod.getRandomIVRLanguage();
        org.junit.Assert.assertNotNull("Data on demand for 'IVRLanguage' failed to initialize correctly", obj);
        String id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'IVRLanguage' failed to provide an identifier", id);
        obj = IVRLanguage.findIVRLanguage(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'IVRLanguage' with identifier '" + id + "'", IVRLanguage.findIVRLanguage(id));
    }
    
}
